mongo_host: localhost:27017
mongo_db: tasty_development

production:
  mongo_host: ds043942.mongolab.com:43942
  mongo_db: heroku_app37588175
  mongo_user: admin
  mongo_password: 10q6w71e

test:
  mongo_host: localhost:27017
  mongo_db: tasty_test

development:
  mongo_host: localhost:27017
  mongo_db: tasty_development
